name: Build and Push Back Docker Image (.NET - Dockerfile handles build)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: todo-deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract backend version from .csproj
        run: |
          csproj_file=$(find backend -name '*.csproj' | head -n 1)
          version=$(sed -En 's/.*<Version>[[:space:]]*([0-9]+\.[0-9]+\.[0-9]+)[[:space:]]*<\/Version>.*/\1/p' $csproj_file)
          if [[ -z "$version" ]]; then
            echo "Error: Could not find a valid <Version> in $csproj_file"
            exit 1
          fi
          echo "BACKEND_VERSION=$version" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          file: backend/Dockerfile
          context: backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/todo-backend:${{ env.BACKEND_VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest
