name: Build and Push Docker Image (.NET - Dockerfile handles build)

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: todo-deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract repository name
        id: extract-name
        run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Extract version from .csproj
        id: get-version
        run: |
          csproj_file=$(find backend -name '*.csproj' | head -n 1)
          version=$(xmllint --xpath "string(//Project/PropertyGroup/Version)" $csproj_file)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          file: backend/Dockerfile
          context: backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo:${{ env.REPO_NAME }}-${{ env.VERSION }}

      - name: Create GitHub Tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            git tag "v${{ env.VERSION }}"
            git push origin --tags
          fi

