# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     environment: todo-deploy

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Copy files to server
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           source: "."
#           target: "/todo"

#       - name: Deploy with Docker Compose
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             cd /todo
#             docker-compose down
#             docker-compose up -d --build
#             docker image prune -f

# .github/workflows/test.yml
name: Simple Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: echo "test"
