on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Confirm SDK and runtime versions
        run: |
          echo "SDK version:"
          dotnet --version
          echo "Installed SDKs:"
          dotnet --list-sdks
          echo "Installed runtimes:"
          dotnet --list-runtimes
